# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactif'), ('E', 'Ex-Member')], max_length=1)),
                ('description', models.TextField(verbose_name='Description')),
                ('speciality', models.TextField(verbose_name='Speciality')),
            ],
            options={
                'verbose_name_plural': 'members',
            },
        ),
    ]
