# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='description',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='speciality',
            new_name='title',
        ),
    ]
