# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160621_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='biography',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
