# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='picture'),
        ),
    ]
