# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnername', models.CharField(max_length=100, verbose_name='partnername')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('website', models.CharField(max_length=300, verbose_name='website')),
            ],
            options={
                'verbose_name_plural': 'partners',
            },
        ),
    ]
