# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ranking',
            field=models.CharField(default='B', max_length=1, verbose_name='ranking'),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
    ]
