# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('github', models.CharField(max_length=100, verbose_name='github')),
                ('status', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'verbose_name_plural': 'projects',
            },
        ),
    ]
